name: Robot Framework Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pkg_resources
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Configure ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --version
        google-chrome --version
        sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Run Robot Framework Tests
      run: |
        mkdir -p output
        robot --outputdir output --variable BROWSER:headlesschrome testes/ || true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results
        path: output/*
        retention-days: 30
