name: Robot Framework Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-faker

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
        chrome --version
        chromedriver --version

    - name: Create output directory
      run: mkdir -p output

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir output testes/

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: robot-test-results
        path: output/
