name: Robot Framework Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
        google-chrome --version
        chromedriver --version

    - name: Run Robot Framework Tests
      run: |
        mkdir -p output
        robot --outputdir output testes/ || true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results
        path: output/*
        retention-days: 30
